#!/bin/bash

PROJECT_NAME=${1:-test_repo}
USER=${2-MatteoLacki}
EMAIL=${3-matteo.lacki@gmail.com}

echo "PROJECT_NAME:" $PROJECT_NAME
echo "user:" $USER
echo "email:" $EMAIL
echo

echo "Create project structure"
mkdir -p $PROJECT_NAME/$PROJECT_NAME
echo "### "$PROJECT_NAME"" >> $PROJECT_NAME/README.md
touch $PROJECT_NAME/__init__.py
touch $PROJECT_NAME/$PROJECT_NAME/__init__.py

echo "Create setup.py and other module intended files"
cat >> $PROJECT_NAME/setup.py << EOF
# This Python file uses the following encoding: utf-8
from setuptools import setup, find_packages

setup(  name='$PROJECT_NAME',
        packages=find_packages(),
        version='0.0.1',
        description='Description.',
        long_description='Long description.',
        author='$USER',
        author_email='$EMAIL',
        url='https://github.com/$USER/$PROJECT_NAME.git',
        keywords=['Great module', 'Devel Inside'],
        classifiers=['Development Status :: 1 - Planning',
                     'License :: OSI Approved :: BSD License',
                     'Intended Audience :: Science/Research',
                     'Topic :: Scientific/Engineering :: Chemistry',
                     'Programming Language :: Python :: 3.6',
                     'Programming Language :: Python :: 3.7'],
        # install_requires=['numpy']
)
EOF

cat >> $PROJECT_NAME/setup.cfg << EOF
[metadata]
description-file = README.md
EOF

cat >> $PROJECT_NAME/Makefile << EOF
PROJECT_NAME = '$PROJECT_NAME'
install:
	virtualenv ve_'$PROJECT_NAME'
	ve_'$PROJECT_NAME'/bin/pip install IPython
	ve_'$PROJECT_NAME'/bin/pip install -e .
upload_test_pypi:
	rm -rf dist || True
	python setup.py sdist
	twine -r testpypi dist/* 
upload_pypi:
	rm -rf dist || True
	python setup.py sdist
	twine upload dist/*
py:
	python -m IPython
EOF

# Create git repo and push the code there
cd $PROJECT_NAME
git init
git add README.md setup.py setup.cfg Makefile __init__.py $PROJECT_NAME/__init__.py
git commit -m "first commit"

# make sure we use ssh instead of https
gh config set git_protocol ssh -h github.com

# Create github repo
gh repo create -y
git branch -M main
git push -u origin main


